name: Build
on:
  pull_request:
  push:
    branches:
      - build_windows_macos 

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            rust_target: x86_64-unknown-linux-gnu
            target: linux_x86_64
          - os: macos-latest
            rust_target: x86_64-apple-darwin
            target: macos_x86_64
          - os: macos-latest
            rust_target: aarch64-apple-darwin
            target: macos_aarch64
          - os: windows-latest
            rust_target: x86_64-pc-windows-msvc
            target: windows_x86_64

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v 
